name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/upload-artifact@v4

      - name: Setup Node
        uses: actions/upload-artifact@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android Platform
        run: cordova platform add android

      - name: Build APK
        run: cordova build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: platforms/android/app/build/outputs/apk/
